import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";

const Hero = styled.div`
  width: 100vw;
  height: 83vh;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  background: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 1rem;
  font-weight: 600;
`;

const CartMovie = styled.div`
  width: 60vw;
  height: 80vh;
  margin: 1rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

export default function DetailMovie({ movie }) {
  return (
    <>
      <Head>
        <title>Detai lMovie Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <CartMovie>
          <Image alt={movie.title} src={movie.image} width={600} height={400} />
          <Heading>{movie.fullTitle}</Heading>
          <Heading>{movie.genres}</Heading>
        </CartMovie>
      </Hero>
    </>
  );
}

export async function getStaticPaths() {
  const res = await fetch(
    "https://imdb-api.com/en/API/Top250Movies/k_ud6q7vrb"
  );

  const dataMovie = await res.json();

  const paths = dataMovie.items.map((movie: any) => ({
    params: {
      id: movie.id,
    },
  }));

  return {
    paths,
    fallback: true,
  };
}

export async function getStaticProps(context: any) {
  const { id } = context.params;

  const res = await fetch(
    `https://imdb-api.com/en/API/Title/k_ud6q7vrb/${id}`,
    {
      method: "GET",
      redirect: "follow",
    }
  );
  const movie = await res.json();

  return {
    props: {
      movie,
    },
  };
}
