import { FC } from "react";
import Head from "next/head";
import styled from "styled-components";

const Hero = styled.div`
  height: 90vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: #fff;
`;

const Heading = styled.h3`
  color: #000;
  font-size: 1rem;
  font-weight: 500;
`;

const About: FC = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>
          This Webiste is a simple web application for viewing the movie list
          from https://imdb-api.com. It is about Take-home assessment Digit
          Sense.
        </Heading>
      </Hero>
    </>
  );
};

export default About;
