import { FC } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";

const Contact: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Contact</h1>
    </>
  );
};

export default Contact;
