import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import { useRouter } from "next/router";

const Hero = styled.div`
  width: 100vw;
  height: 83vh;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  background: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 1rem;
  font-weight: 600;
`;

const CartMovie = styled.div`
  width: 300px;
  height: 250px;
  margin: 1rem;
  cursor: pointer;
`;

export default function Home({ dataMovie }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        {Array.isArray(dataMovie.items) &&
          dataMovie.items.map((movie: any) => (
            <CartMovie
              key={movie.id}
              onClick={() => router.push(`movie/${movie.id}`)}
            >
              <Image
                alt={movie.title}
                src={movie.image}
                width={300}
                height={200}
              />
              <Heading>{movie.fullTitle}</Heading>
            </CartMovie>
          ))}
      </Hero>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://imdb-api.com/en/API/Top250Movies/k_ud6q7vrb"
  );

  const dataMovie = await res.json();

  return {
    props: {
      dataMovie,
    },
  };
}
